export const categories = [
  {
    id: 1,
    name: 'Sans',
    slug: 'sans',
  },
  {
    id: 2,
    name: 'Serif',
    slug: 'serif',
  },
  {
    id: 3,
    name: 'Slab',
    slug: 'slab',
  },
  {
    id: 4,
    name: 'Display',
    slug: 'display',
  },
  {
    id: 5,
    name: 'Script',
    slug: 'script',
  },
  {
    id: 6,
    name: 'Mono',
    slug: 'mono',
  },
  {
    id: 7,
    name: 'Variable',
    slug: 'variable',
  },
];

export const LandingPage = {
  Blogs: [
    {
      id: 1,
      img: '/produk/produk1.png',
      title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
      desc: 'Prepare for a thrilling journey into the world of motion. That’s right: Creative Market is launching a brand-new cat',
    },
    {
      id: 2,
      img: '/produk/produk2.jpg',
      title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
      desc: 'Prepare for a thrilling journey into the world of motion. That’s right: Creative Market is launching a brand-new cat',
    },
    {
      id: 3,
      img: '/produk/produk1.png',
      title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
      desc: 'Prepare for a thrilling journey into the world of motion. That’s right: Creative Market is launching a brand-new cat',
    },
    {
      id: 4,
      img: '/produk/produk1.png',
      title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
      desc: 'Prepare for a thrilling journey into the world of motion. That’s right: Creative Market is launching a brand-new cat',
    },
  ],
};

export const Produk = {
  Fonts: [
    {
      id: 1,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 2,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 3,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 4,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 5,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 6,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 7,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 8,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
  ],
  newRelease: [
    {
      id: 1,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 2,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 3,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 4,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
  ],
  staffPick: [
    {
      id: 1,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 2,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 3,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 4,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
  ],
};

export const Blogs = {
  menuContents: [
    {
      id: 1,
      title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
    },
    {
      id: 2,
      title: 'What you need to',
    },
    {
      id: 3,
      title: 'How to Apply',
    },
    {
      id: 4,
      title: 'The creative challenge',
    },
  ],
  blogsContents: {
    id: 1,
    title: 'Bring Your Vibe to Life with Over 5 Million New Videos',
    date: 'July 11, 2022',
    img: '/produk/produk1.png',
    p: 'Prepare for a thrilling journey into the world of motion. That’s right: Creative Market is launching a brand-new category, and it’s set to move your design worldThese aren’t your run-of-the-mill clips. We’re talking original, thought-provoking footage that’s been intentionally captured by professional creatives around the world. Our new video catalog is all about compelling storytelling. Video is immersive, dynamic, and let’s face it – the king of engagement.Starting today, all these high-quality videos are available for one-off licensing, or if you’re a Creative Market member, you can score up to 20% off their base price. It’s showtime!Create Stunning Reels: Snag an abstract modern background video, overlay some text, and voila! You’ve got a Reel that’s sure to stop your audience in their tracks.Website Overhaul: Add a layer of dynamism to your website with full-screen video backgrounds that instantly catch the eye.Product Promotion: Showcasing a new product? Use a well-shot video to bring its features to life and make a lasting impression on your customers.Email Marketing: Embed short, captivating videos in your newsletters to increase click-through rates and keep your subscribers engaged.Social Media Ads: Utilize attention-grabbing videos in your ads to boost conversion rates and ramp up your brand’s online presence',
  },
  reviews: '30',
  totalStars: '5',
};

export const detailPages = {
  detail: {
    id: 1,
    categories: 'Fonts',
    subCategories: 'Sans Serif',
    img: '/produk/produk1.png',
    imagesItems: [
      {
        id: 1,
        img: '/produk/produk1.png',
      },
      {
        id: 2,
        img: '/produk/produk2.jpg',
      },
      {
        id: 3,
        img: '/produk/produk1.png',
      },
      {
        id: 4,
        img: '/produk/produk3.jpg',
      },
    ],
    title: 'Bison - A Powerful Sans Serif',
    commercial: '21',
    personal: '40',
    totalStars: 12,
    starNumber: 3,
    desc: 'Introducing the Strike Destiny Font,handcrafted brush fonts! A bold, free-flowing and confident brush font. nStrike Destiny is a script font with a stroke style.This font is suitable for use from handwritten quotes, to product packaging, merchandise and branding projects,Complete with Uppercase and Lowercase, Numberic, Ligature, and coupled with this sweep alternative it will look very impressive.',
  },
  user: {
    id: 1,
    nameToko: 'Nestype',
    imgToko: '/produk/profil.jpg',
    descToko: "Just love making pretty things :) Might as well earn some beans while I'm doing it :) Feel free to email me with any of your",
  },
  produkToko: [
    {
      id: 1,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 2,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 4,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 3,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
  ],
  reviews: [
    {
      id: 1,
      nameUser: 'John Stones',
      imgUser: '/produk/profil.jpg',
      totalStars: 4,
      comment:
        'We used this font for our wedding invitations because it was in the template and subsequently I bought it to use on our wedding homepage, as well. I really like the font as it is both well readable and looks elegant but also wild at the same time',
    },
    {
      id: 2,
      nameUser: 'John Stones',
      imgUser: '/produk/profil.jpg',
      totalStars: 4,
      comment:
        'We used this font for our wedding invitations because it was in the template and subsequently I bought it to use on our wedding homepage, as well. I really like the font as it is both well readable and looks elegant but also wild at the same time',
    },
    {
      id: 2,
      nameUser: 'John Stones',
      imgUser: '/produk/profil.jpg',
      totalStars: 4,
      comment:
        'We used this font for our wedding invitations because it was in the template and subsequently I bought it to use on our wedding homepage, as well. I really like the font as it is both well readable and looks elegant but also wild at the same time',
    },
  ],
};

export const tokoPages = {
  user: {
    id: 1,
    nameToko: 'Nestype',
    imgToko: '/produk/profil.jpg',
    descToko: "Just love making pretty things :) Might as well earn some beans while I'm doing it :) Feel free to email me with any of your",
  },
  produkToko: [
    {
      id: 1,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 2,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 3,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 4,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 5,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 6,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk2.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 7,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk4.jpg',
      imgToko: '/produk/profil.jpg',
    },
    {
      id: 8,
      name: 'Bison - A Powerful Sans Serif',
      slug: 'bison - a powerful sans serif',
      totalStars: 12,
      starNumber: 3,
      sales: 200,
      price: 20,
      nameToko: 'Ellen luf',
      categories: 'Fonts',
      img: '/produk/produk1.png',
      imgToko: '/produk/profil.jpg',
    },
  ],
};
